export const USER = {
  username: process.env.VUE_APP_USERNAME,
  password: process.env.VUE_APP_PASSWORD
}

export const COLORS = {
  background: '#FFFFFF',
  surface: '#FFFFFF',
  primary: '#583896',
  secondary: '#583896',
}

export const DUMMY_DATA = [
  {symbol:"AED",description:"AED - United Arab Emirates Dirham"},
  {symbol:"AFN",description:"AFN - Afghan Afghani"},
  {symbol:"ALL",description:"ALL - Albanian Lek"},
  {symbol:"AMD",description:"AMD - Armenian Dram"},
  {symbol:"ANG",description:"ANG - Netherlands Antillean Guilder"},
  {symbol:"AOA",description:"AOA - Angolan Kwanza"},
  {symbol:"ARS",description:"ARS - Argentine Peso"},
  {symbol:"AUD",description:"AUD - Australian Dollar"},
  {symbol:"AWG",description:"AWG - Aruban Florin"},                              
  {symbol:"AZN",description:"AZN - Azerbaijani Manat"},                              
  {symbol:"BAM",description:"BAM - Bosnia-Herzegovina Convertible Mark"},                              
  {symbol:"BBD",description:"BBD - Barbadian Dollar"},                              
  {symbol:"BGN",description:"BGN - Bulgarian Lev"},                              
  {symbol:"BHD",description:"BHD - Bahraini Dinar"},                              
  {symbol:"BIF",description:"BIF - Burundian Franc"},                              
  {symbol:"BMD",description:"BMD - Bermudan Dollar"},                              
  {symbol:"BND",description:"BND - Brunei Dollar"},                              
  {symbol:"BOB",description:"BOB - Bolivian Boliviano"},                              
  {symbol:"BRL",description:"BRL - Brazilian Real"},                              
  {symbol:"BSD",description:"BSD - Bahamian Dollar"},                              
  {symbol:"BSD",description:"BSD - Bahamian Dollar"},
  {symbol:"BTN",description:"BTN - Bhutanese Ngultrum"},
  {symbol:"BWP",description:"BWP - Botswanan Pula"},
  {symbol:"BZD",description:"BZD - Belize Dollar"},
  {symbol:"CAD",description:"CAD - Canadian Dollar"},
  {symbol:"CDF",description:"CDF - Congolese Franc"},
  {symbol:"CHF",description:"CHF - Swiss Franc"},
  {symbol:"CLF",description:"CLF - Chilean Unit of Account UF"},
  {symbol:"CLP",description:"CLP - Chilean Peso"},
  {symbol:"CNH",description:"CNH - Chinese Yuan Offshore"},
  {symbol:"CNY",description:"CNY - Chinese Yuan"},
  {symbol:"COP",description:"COP - Colombian Peso"},
  {symbol:"CUP",description:"CUP - Cuban Peso"},
  {symbol:"CVE",description:"CVE - Cape Verdean Escudo"},
  {symbol:"CZK",description:"CZK - Czech Republic Koruna"},
  {symbol:"DJF",description:"DJF - Djiboutian Franc"},
  {symbol:"DKK",description:"DKK - Danish Krone"},
  {symbol:"DOP",description:"DOP - Dominican Peso"},
  {symbol:"DZD",description:"DZD - Algerian Dinar"},
  {symbol:"EGP",description:"EGP - Egyptian Pound"},
  {symbol:"ERN",description:"ERN - Eritrean Nakfa"},
  {symbol:"ETB",description:"ETB - Ethiopian Birr"},
  {symbol:"EUR",description:"EUR - Euro"},
  {symbol:"FJD",description:"FJD - Fijian Dollar"},
  {symbol:"FKP",description:"FKP - Falkland Islands Pound"},
  {symbol:"GBP",description:"GBP - British Pound Sterling"},
  {symbol:"GEL",description:"GEL - Georgian Lari"},
  {symbol:"GHS",description:"GHS - Ghanaian Cedi"},
  {symbol:"GIP",description:"GIP - Gibraltar Pound"},
  {symbol:"GMD",description:"GMD - Gambian Dalasi"},
  {symbol:"GNF",description:"GNF - Guinean Franc"},
  {symbol:"GTQ",description:"GTQ - Guatemalan Quetzal"},
  {symbol:"GYD",description:"GYD - Guyanaese Dollar"},
  {symbol:"HKD",description:"HKD - Hong Kong Dollar"},
  {symbol:"HNL",description:"HNL - Honduran Lempira"},
  {symbol:"HRK",description:"HRK - Croatian Kuna"},
  {symbol:"HTG",description:"HTG - Haitian Gourde"},
  {symbol:"HUF",description:"HUF - Hungarian Forint"},
  {symbol:"ICP",description:"ICP - Internet Computer"},
  {symbol:"IDR",description:"IDR - Indonesian Rupiah"},
  {symbol:"ILS",description:"ILS - Israeli New Sheqel"},
  {symbol:"INR",description:"INR - Indian Rupee"},
  {symbol:"IQD",description:"IQD - Iraqi Dinar"},
  {symbol:"IRR",description:"IRR - Iranian Rial"},
  {symbol:"ISK",description:"ISK - Icelandic Krona"},
  {symbol:"JEP",description:"JEP - Jersey Pound"},
  {symbol:"JMD",description:"JMD - Jamaican Dollar"},
  {symbol:"JOD",description:"JOD - Jordanian Dinar"},
  {symbol:"JPY",description:"JPY - Japanese Yen"},
  {symbol:"KES",description:"KES - Kenyan Shilling"},
  {symbol:"KGS",description:"KGS - Kyrgystani Som"},
  {symbol:"KHR",description:"KHR - Cambodian Riel"},
  {symbol:"KMF",description:"KMF - Comorian Franc"},
  {symbol:"KPW",description:"KPW - North Korean Won"},
  {symbol:"KRW",description:"KRW - South Korean Won"},
  {symbol:"KWD",description:"KWD - Kuwaiti Dinar"},
  {symbol:"KYD",description:"KYD - Cayman Islands Dollar"},
  {symbol:"KZT",description:"KZT - Kazakhstani Tenge"},
  {symbol:"LAK",description:"LAK - Laotian Kip"},
  {symbol:"LBP",description:"LBP - Lebanese Pound"},
  {symbol:"LKR",description:"LKR - Sri Lankan Rupee"},
  {symbol:"LRD",description:"LRD - Liberian Dollar"},
  {symbol:"LSL",description:"LSL - Lesotho Loti"},
  {symbol:"LYD",description:"LYD - Libyan Dinar"},
  {symbol:"MAD",description:"MAD - Moroccan Dirham"},
  {symbol:"MDL",description:"MDL - Moldovan Leu"},
  {symbol:"MGA",description:"MGA - Malagasy Ariary"},
  {symbol:"MKD",description:"MKD - Macedonian Denar"},
  {symbol:"MMK",description:"MMK - Myanma Kyat"},
  {symbol:"MNT",description:"MNT - Mongolian Tugrik"},
  {symbol:"MOP",description:"MOP - Macanese Pataca"},
  {symbol:"MRO",description:"MRO - Mauritanian Ouguiya (pre-2018)"},
  {symbol:"MRU",description:"MRU - Mauritanian Ouguiya"},
  {symbol:"MUR",description:"MUR - Mauritian Rupee"},
  {symbol:"MVR",description:"MVR - Maldivian Rufiyaa"},
  {symbol:"MWK",description:"MWK - Malawian Kwacha"},
  {symbol:"MXN",description:"MXN - Mexican Peso"},
  {symbol:"MYR",description:"MYR - Malaysian Ringgit"},
  {symbol:"MZN",description:"MZN - Mozambican Metical"},
  {symbol:"NAD",description:"NAD - Namibian Dollar"},
  {symbol:"NGN",description:"NGN - Nigerian Naira"},
  {symbol:"NOK",description:"NOK - Norwegian Krone"},
  {symbol:"NPR",description:"NPR - Nepalese Rupee"},
  {symbol:"NZD",description:"NZD - New Zealand Dollar"},
  {symbol:"OMR",description:"OMR - Omani Rial"},
  {symbol:"PAB",description:"PAB - Panamanian Balboa"},
  {symbol:"PEN",description:"PEN - Peruvian Nuevo Sol"},
  {symbol:"PGK",description:"PGK - Papua New Guinean Kina"},
  {symbol:"PHP",description:"PHP - Philippine Peso"},
  {symbol:"PKR",description:"PKR - Pakistani Rupee"},
  {symbol:"PLN",description:"PLN - Polish Zloty"},
  {symbol:"PYG",description:"PYG - Paraguayan Guarani"},
  {symbol:"QAR",description:"QAR - Qatari Rial"},
  {symbol:"RON",description:"RON - Romanian Leu"},
  {symbol:"RSD",description:"RSD - Serbian Dinar"},
  {symbol:"RUB",description:"RUB - Russian Ruble"},
  {symbol:"RUR",description:"RUR - Old Russian Ruble"},
  {symbol:"RWF",description:"RWF - Rwandan Franc"},
  {symbol:"SAR",description:"SAR - Saudi Riyal"},
  {symbol:"SBDf",description:"SBDf - Solomon Islands Dollar"},
  {symbol:"SCR",description:"SCR - Seychellois Rupee"},
  {symbol:"SDG",description:"SDG - Sudanese Pound"},
  {symbol:"SDR",description:"SDR - Special Drawing Rights"},
  {symbol:"SEK",description:"SEK - Swedish Krona"},
  {symbol:"SGD",description:"SGD - Singapore Dollar"},
  {symbol:"SHP",description:"SHP - Saint Helena Pound"},
  {symbol:"SLL",description:"SLL - Sierra Leonean Leone"},
  {symbol:"SOS",description:"SOS - Somali Shilling"},
  {symbol:"SRD",description:"SRD - Surinamese Dollar"},
  {symbol:"SYP",description:"SYP - Syrian Pound"},
  {symbol:"SZL",description:"SZL - Swazi Lilangeni"},
  {symbol:"THB",description:"THB - Thai Baht"},
  {symbol:"TJS",description:"TJS - Tajikistani Somoni"},
  {symbol:"TMT",description:"TMT - Turkmenistani Manat"},
  {symbol:"TND",description:"TND - Tunisian Dinar"},
  {symbol:"TOP",description:"TOP - Tongan Pa'anga"},
  {symbol:"TRY",description:"TRY - Turkish Lira"},
  {symbol:"TTD",description:"TTD - Trinidad and Tobago Dollar"},
  {symbol:"TWD",description:"TWD - New Taiwan Dollar"},
  {symbol:"TZS",description:"TZS - Tanzanian Shilling"},
  {symbol:"UAH",description:"UAH - Ukrainian Hryvnia"},
  {symbol:"UGX",description:"UGX - Ugandan Shilling"},
  {symbol:"USD",description:"USD - United States Dollar"},
  {symbol:"UYU",description:"UYU - Uruguayan Peso"},
  {symbol:"UZS",description:"UZS - Uzbekistan Som"},
  {symbol:"VND",description:"VND - Vietnamese Dong"},
  {symbol:"VUV",description:"VUV - Vanuatu Vatu"},
  {symbol:"WST",description:"WST - Samoan Tala"},
  {symbol:"XAF",description:"XAF - CFA Franc BEAC"},
  {symbol:"XCD",description:"XCD - East Caribbean Dollar"},
  {symbol:"XDR",description:"XDR - Special Drawing Rights"},
  {symbol:"XOF",description:"XOF - CFA Franc BCEAO"},
  {symbol:"XPF",description:"XPF - CFP Franc"},
  {symbol:"YER",description:"YER - Yemeni Rial"},
  {symbol:"ZAR",description:"ZAR - South African Rand"},
  {symbol:"ZMW",description:"ZMW - Zambian Kwacha"},
  {symbol:"ZWL",description:"ZWL - Zimbabwean Dollar"}
]